### ISSUE TITLE
With Specflow 2.1, AfterScenario is not called

### ISSUE THREAD

**Issue by tjgould1983** [MikeMugu/Zukini#8]
After upgrading to Specflow 2.1 (from 1.9), the AfterScenario method is no longer being called resulting in the browser not being closed and screenshots not being take if the scenario fails. Would you be able to see if this can be fixed by a change in the Zukini project?

**Comment by MikeMugu** [comment]
I can take a look.

**Comment by MikeMugu** [comment]
Hello,

I upgraded both the Zukini and Zukini.Examples.Features project to use
SpecFlow 2.1 and the AfterScenario fired for me. I have updated the code
and committed to the master branch if you want to try and pull down and
test.

I will work on upgrading Coypu and the WebDriver dependencies this weekend.

Thanks,

**Comment by jedsmallwood** [comment]
You're so bored in Chicago that you need to work on Zukini?
